### ISSUE TITLE
v4.0 release todo (2022)

### ISSUE THREAD

**Issue by Correct-Syntax** [BibleNotify/BibleNotify#4]
Its now been over a year since the original version. Bible Notify v4.0 will be a major update. The following is a TODO list for the new version:

- [x] Update app design
- [x] Update graphics
- [x] ~~Add more scriptures~~ moved to v4.1
- [x] Check compatibility with Android 12
- [x] Update project website

CC @sundrycode

**Comment by Correct-Syntax** [comment]
@sundrycode what do you think of this concept for the new logo?

![bn-logo-idea](https://user-images.githubusercontent.com/60711001/148310227-c3d94369-445d-4f23-b30c-a7c2bf3742c3.png)

**Comment by sundrycode** [comment]
I'm not sure about the font, but otherwise I like it.

**Comment by Correct-Syntax** [comment]
![16_objects@2x](https://user-images.githubusercontent.com/60711001/148666987-7c91a2a1-6c04-4ccc-ba26-14cd08f081ef.png)

**Comment by Correct-Syntax** [comment]
![image](https://user-images.githubusercontent.com/60711001/148667129-582afefc-d321-49bc-ae4e-965177355166.png)
